import {
  CREATE_CLAUDE_AGENT_SESSION_ROUTE,
  DELETE_CLAUDE_AGENT_SESSION_ROUTE,
  FORK_CLAUDE_AGENT_SESSION_ROUTE,
  GET_CLAUDE_AGENT_ROUTE,
  GET_CLAUDE_AGENT_SESSION_ROUTE,
  LIST_CLAUDE_AGENTS_ROUTE,
  LIST_CLAUDE_AGENT_SESSIONS_ROUTE,
  RESOLVE_CLAUDE_AGENT_APPROVAL_ROUTE,
  RESOLVE_CLAUDE_AGENT_QUESTION_ROUTE,
  STREAM_CLAUDE_AGENT_TURN_ROUTE,
  UPDATE_CLAUDE_AGENT_SESSION_ROUTE,
} from '../../handlers/claude-agents';

export const CLAUDE_AGENTS_ROUTES = [
  LIST_CLAUDE_AGENTS_ROUTE,
  GET_CLAUDE_AGENT_ROUTE,
  LIST_CLAUDE_AGENT_SESSIONS_ROUTE,
  GET_CLAUDE_AGENT_SESSION_ROUTE,
  CREATE_CLAUDE_AGENT_SESSION_ROUTE,
  STREAM_CLAUDE_AGENT_TURN_ROUTE,
  FORK_CLAUDE_AGENT_SESSION_ROUTE,
  UPDATE_CLAUDE_AGENT_SESSION_ROUTE,
  DELETE_CLAUDE_AGENT_SESSION_ROUTE,
  RESOLVE_CLAUDE_AGENT_APPROVAL_ROUTE,
  RESOLVE_CLAUDE_AGENT_QUESTION_ROUTE,
] as const;
